### ISSUE TITLE
Google Maps is complaining

### ISSUE THREAD

**Issue by SethTisue** [scalaspace/scalaspace.github.io#78]
when I load the site (in either Safari or Chrome) I see:

<img width="400" alt="screen shot 2019-02-07 at 2 25 01 pm" src="https://user-images.githubusercontent.com/161079/52446908-39ac1600-2ae4-11e9-8eed-aefe5daed45a.png">

**Comment by propensive** [comment]
I presume it's using an old version of the Google Maps API, and I need to upgrade it.

Would you have time to take a quick look at it, @jarrodu?

**Comment by jarrodu** [comment]
It looks like a billing issue related to the API key.

If I remember correctly I don't have control over the API key for this site.

https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=keyless#api-key-and-billing-errors

**Comment by SethTisue** [comment]
ping @propensive

**Comment by jarrodu** [comment]
@propensive Can you give me this site? I am interested in developing it more.

**Comment by propensive** [comment]
@jarrodu I'm probably being a bit dumb... and it's been a long time since I set up the Maps API. I'm happy to hand over access to the API, but have you any idea where I need to go? I fumbled around in Google Cloud Platform for a while, without seeing anything relating to my existing details...

It might be easier to set up a new API key for scala.space. It looks like the Maps API is split into several different options, so if you tell me what you need, I can probably organize it!

**Comment by jarrodu** [comment]
Hi. I will be on vacation for two weeks. When I get back we can sort it out. :+1:

**Comment by jarrodu** [comment]
I fixed it. I created an API key with my personnel Google account and then added it to the site.
